package com.bright_side_it.fliesenui.generator.logic;

import com.bright_side_it.fliesenui.screendefinition.model.ScreenDefinition;

public class JSListChooserDialogCreatorLogic {
	public StringBuilder createListChooserDialogMethods(ScreenDefinition screenDefinition, String screenIDPrefix) {
		StringBuilder sb = new StringBuilder();
		
		sb.append("    $scope.showListChooser = function(parameter){\n");
		sb.append("    	$scope.listChooserReferenceID = parameter.referenceID;\n");
		sb.append("    	$scope.listChooserCallbackData = parameter.callbackData;\n");
		sb.append("    	$scope.listChooserTitle = parameter.title;\n");
		sb.append("    	$scope.listChooserMultiselect = parameter.multiSelect;\n");
		sb.append("    	$scope.listChooserShowIcons = parameter.showIcons;\n");
		sb.append("    	$scope.listChooserOKText = parameter.okText;\n");
		sb.append("    	$scope.listChooserCancelText = parameter.cancelText;\n");
		sb.append("    	$scope.listChooserItems = parameter.items;\n");
		sb.append("    	$scope.listChooserShowFilter = parameter.showFilter;\n");
		sb.append("        $scope.listChooserFilter = \"\";\n");
		sb.append("    	\n");
		sb.append("        $mdDialog.show({\n");
		sb.append("            controller: ListChooserDialogController,\n");
		sb.append("            parent: angular.element(document.body),\n");
		sb.append("            scope: $scope,\n");
		sb.append("            preserveScope: true, \n");
		sb.append("            clickOutsideToClose:true,\n");
		sb.append("            template:\n");
		sb.append("			     '<md-dialog aria-label=\"{{listChooserTitle}}\" style=\"width: 80%;height: 80%;\">'\n");
		sb.append("               + '  <form ng-cloak>'\n");
		sb.append("               + '    <md-toolbar>'\n");
		sb.append("               + '      <div class=\"md-toolbar-tools\">'\n");
		sb.append("               + '        <h2>{{listChooserTitle}}</h2>'\n");
		sb.append("               + '      </div>'\n");
		sb.append("               + '    </md-toolbar>'\n");
		sb.append("               + '    <md-dialog-content>'\n");
		sb.append("               + '      <div class=\"md-dialog-content\">'\n");
		sb.append("               + '	    <span ng-show=\"listChooserShowFilter\" > '\n");
		sb.append("               + '			<md-input-container class=\"md-block\" flex-gt-sm>'\n");
		sb.append("               + '				<label>Search</label>'\n");
		sb.append("               + '				<input ng-model=\"listChooserFilter\" style=\"width:99%\">'\n");
		sb.append("               + '			  </md-input-container>'\n");
		sb.append("               + '		</span>'\n");
		sb.append("               + '		<table style=\"width:100%; overflow-y: scroll;\">'\n");
		sb.append("               + '			<tr ng-repeat=\"i in listChooserItems | filter : {\\'label\\' : listChooserFilter}\" '\n");
		sb.append("               + '			    ng-click=\"listChooser_rowClicked($event, i.id, i)\" '\n");
		sb.append("               + '			    style=\"border-color:#999999;border-bottom-style: solid;border-width: 1px; background-color:{{rowBackgroundColor}}\" '\n");
		sb.append("               + '			    layout=\"row\" '\n");
		sb.append("               + '			    layout-wrap=\"\" '\n");
		sb.append("               + '			    ng-init=\"rowBackgroundColor=\\'white\\';\" '\n");
		sb.append("               + '			    ng-mouseleave=\"rowHover=false;rowBackgroundColor=\\'white\\';\"'\n");
		sb.append("               + '			    ng-mouseover=\"rowHover=true;rowBackgroundColor=\\'#f3f3f3\\';\">'\n");
		sb.append("               + '			    <td ng-if=\"listChooserMultiselect && i.selected\"  style=\"min-height:60px; padding-left:15px; padding-top:15px;\"><img src=\"img/_checkbox_checked.png\"   width=\"20\"/></td>'\n");
		sb.append("               + '			    <td ng-if=\"listChooserMultiselect && !i.selected\" style=\"min-height:60px; padding-left:15px; padding-top:15px;\"><img src=\"img/_checkbox_unchecked.png\" width=\"20\"/></td>'\n");
		sb.append("               + '			    <td ng-if=\"listChooserShowIcons\" style=\"min-height:60px; padding-left:15px; padding-top:15px;\"><img ng-src=\"img/{{imageAssetIDToName[i.imageAssetID]}}\" width=\"40px\" height=\"40px\"/></td>'\n");
		sb.append("               + '				<td style=\"word-wrap: break-word;min-height:60px; padding-left:15px; padding-top:15px;\">{{i.label}}</td>'\n");
		sb.append("               + '			</tr>'\n");
		sb.append("               + '		</table>'\n");
		sb.append("               + '      </div>'\n");
		sb.append("               + '    </md-dialog-content>'\n");
		sb.append("               + ''\n");
		sb.append("               + '    <md-dialog-actions layout=\"row\">'\n");
		sb.append("               + '      <span flex></span>'\n");
		sb.append("               + '      <md-button ng-click=\"cancel();\">'\n");
		sb.append("               + '       {{listChooserCancelText}}'\n");
		sb.append("               + '      </md-button>'\n");
		sb.append("               + '      <md-button ng-click=\"hide();listChooser_okClicked();\" ng-visible=\"listChooserMultiselect\">'\n");
		sb.append("               + '        {{listChooserOKText}}'\n");
		sb.append("               + '      </md-button>'\n");
		sb.append("               + '    </md-dialog-actions>'\n");
		sb.append("               + '  </form>'\n");
		sb.append("               + '</md-dialog>'\n");
		sb.append("        })\n");
		sb.append("        .then(function(answer) {\n");
		sb.append("        }, function() {\n");
		sb.append("              $scope.listChooser_cancelled();\n");
		sb.append("        });\n");
		sb.append("    }\n");
		sb.append("      \n");
		sb.append("    function ListChooserDialogController($scope, $mdDialog) {\n");
		sb.append("        $scope.hide = function() {\n");
		sb.append("    	    $mdDialog.hide();\n");
		sb.append("    	};\n");
		sb.append("    	$scope.cancel = function() {\n");
		sb.append("    	    $mdDialog.cancel();\n");
		sb.append("    	};\n");
		sb.append("        $scope.answer = function(answer) {\n");
		sb.append("    	    $mdDialog.hide(answer);\n");
		sb.append("    	};\n");
		sb.append("    	    \n");
		sb.append("    	$scope.listChooser_rowClicked = function (event, itemID, item) {\n");
		sb.append("    	    if (!event.defaultPrevented) {\n");
		sb.append("    	        console.log(\"clicked row with itemID = \" + itemID + \", old selected = \" + item.selected);\n");
		sb.append("                if ($scope.listChooserMultiselect){\n");
		sb.append("    	            item.selected = !item.selected;\n");
		sb.append("    	        	console.log(\"new selected = \" + item.selected);\n");
		sb.append("    	        } else if (!$scope.listChooserMultiselect){\n");
		sb.append("    	            //:clear old selection\n");
		sb.append("    	        	for (i = 0; i < $scope.listChooserItems.length; i++){\n");
		sb.append("    	        	    $scope.listChooserItems[i].selected = false;\n");
		sb.append("    	            }\n");
		sb.append("    	            //: select item\n");
		sb.append("        	        item.selected = !item.selected;\n");
		sb.append("        	        	  \n");
		sb.append("    	        	$mdDialog.hide(\"\");\n");
		sb.append("        	        $scope.listChooser_okClicked();        		  \n");
		sb.append("    	        }\n");
		sb.append("    	    }\n");
		sb.append("        };\n");
		sb.append("    } \n");
		sb.append("      \n");
		sb.append("    $scope.listChooser_okClicked = function () {\n");
		sb.append("        console.log(\"clicked ok\");\n");
		sb.append("        var selectedIDs = [];\n");
		sb.append("	       for (i = 0; i < $scope.listChooserItems.length; i++){\n");
		sb.append("            var item = $scope.listChooserItems[i];\n");
		sb.append("            if (item.selected){\n");
		sb.append("//			    console.log(\"selected id: \" + item.id);\n");
		sb.append("            selectedIDs.push(item.id);\n");
		sb.append("            }\n");
		sb.append("        }\n");
		sb.append("        console.log(\"selected ids: \" + selectedIDs);\n");
		sb.append("        var request = " + screenIDPrefix + "createRequest(\"onListChooserResult\");\n");
		sb.append("        request.parameters[\"referenceID\"] = $scope.listChooserReferenceID;\n");
		sb.append("        request.parameters[\"callbackData\"] = $scope.listChooserCallbackData;\n");
		sb.append("        request.parameters[\"selectedIDs\"] = selectedIDs;\n");
		sb.append("        " + screenIDPrefix + "executeRequest(request);\n");
		sb.append("    }\n");
		sb.append("\n");
		sb.append("    $scope.listChooser_cancelled = function () {\n");
		sb.append("	    console.log(\"list chooser: cancelled\");\n");
		sb.append("        var request = " + screenIDPrefix + "createRequest(\"onListChooserResult\");\n");
		sb.append("        request.parameters[\"referenceID\"] = $scope.listChooserReferenceID;\n");
		sb.append("        request.parameters[\"callbackData\"] = $scope.listChooserCallbackData;\n");
		sb.append("        request.parameters[\"selectedIDs\"] = null;\n");
		sb.append("        " + screenIDPrefix + "executeRequest(request);\n");
		sb.append("    }\n");
		sb.append("      \n");

		
		return sb;
	}
}
