package com.bright_side_it.fliesenui.screendefinition.model;

public class ResourceDefinitionProblem {
    public enum ProblemType {
        WIDGET_TABLE_UNKNOWN_DTO_SPECIFIED, WIDGET_TABLE_NO_FIELD_IN_DTO_SPECIFIED, WIDGET_TABLE_DTO_TYPE_UNKNOWN, WIDGET_TABLE_UNKNOWN_DTO_FIELD, WIDGET_TABLE_DTO_BASIC_TYPE_WITH_NESTED_TYPE, WIDGET_TABLE_DTO_SUB_TYPE_UNKNOWN, WIDGET_TABLE_DTO_IS_NOT_A_LIST, WIDGET_TABLE_ITEM_DTO_FIELD_UNKNOWN, WIDGET_TABLE_ID_DTO_FIELD_DOES_NOT_EXIST, WIDGET_TABLE_ID_DTO_FIELD_HAS_WRONG_TYPE, WIDGET_TABLE_ITEM_FIELD_HAS_WRONG_TYPE, ID_PROBLEM_ID_EMPTY, ID_PROBLEM_ID_DOES_NOT_START_WITH_LOWER_CHAR, ID_PROBLEM_ID_CONTAINS_WRONG_CHAR, ID_PROBLEM_ID_USED_MULTIPLE_TIMES, BAR_PROBLEM_SUM_NOT_100, BASIC_WIDGET_UNKNOWN_TYPE, WIDGET_TABLE_NO_COLUMNS, SPACE_WIDGET_MISSING_HEIGHT, SPACE_WIDGET_HEIGHT_TOO_SMALL, TEXT_FIELD_WIDGET_UNEXPECTED_HEIGHT, BASIC_WIDGET_MISSING_ATTRIBUTE, BASIC_WIDGET_UNEXPECTED_ATTRIBUTE, WIDGET_TABLE_WRONG_SIZE, WIDGET_TABLE_WRONG_TOTAL_COLUMN_SIZE, CELL_WRONG_COLOR_VALUE, EVENT_PARAMETER_UNKNOWN_DTO, EVENT_PARAMETER_UNKNOWN_NO_DTO_AND_NO_WIDGET, EVENT_PARAMETER_UNKNOWN_WIDGET, EVENT_PARAMETER_MISSING_WIDGET_PROPERTY, CELL_WRONG_HEIGHT, WIDGET_TABLE_WRONG_HEIGHT, WRONG_XML_NODE_NAME, INVALID_XML_DATA, WIDGET_TABLE_COLUMN_WITHOUT_ITEMS, WIDGET_TABLE_ITEM_MISSING_ID, LABEL_WIDGET_MISSING_ID, WIDGET_TABLE_NO_DTO_SPECIFIED, WIDGET_TABLE_ID_DTO_FIELD_IS_MISSING, EVENT_PARAMETER_WRONG_WIDGET_TYPE_REFERENCED, EVENT_PARAMETER_WRONG_WIDGET_PROPERTY, LABEL_WIDGET_UNEXPECTED_STYLE, BUTTON_WIDGET_UNEXPECTED_STYLE, PLUGIN_INSTANCE_UNKNOWN_TYPE, PLUGIN_INSTANCE_MISSING_ID, PLUGIN_PARAMETER_UNEXPECTED, PLUGIN_PARAMETER_MISSING, EVENT_PARAMETER_UNKNOWN_PLUGIN_INSTANCE, EVENT_PARAMETER_UNKNOWN_PLUGIN_DEFINITION, EVENT_PARAMETER_UNKNOWN_PLUGIN_VARIABLE, IMAGE_SOURCE_IMAGE_RESOURCE_UNKNOWN, IMAGE_SOURCE_UNKNOWN_FORMAT, IMAGE_SOUCE_MULTIPLE_LOCATIONS, IMAGE_SOUCE_MISSING_LOCATION, IMAGE_SOUCE_MISSING_FORMAT, IMAGE_ASSET_DUPLICATE_ID, IMAGE_SOURCE_WRONG_WIDTH, IMAGE_SOURCE_WRONG_HEIGHT, WIDGET_TABLE_ITEM_UNEXPECTED_TEXT, WIDGET_TABLE_ITEM_UNEXPECTED_TEXT_DTO_FIELD, WIDGET_TABLE_ITEM_MISSING_IMAGE_SOURCE, BASIC_WIDGET_WITH_IMAGE_SOURCE_IS_MISSING_ID, UNEXPECTED_XML_ATTRIBUTE, WIDGET_TABLE_ITEM_IMAGE_DTO_FIELD_HAS_WRONG_TYPE, SCREEN_DEFINITION_UNKNOWN_PARAMETER_DTO, SCREEN_DEFINITION_UNKNOWN_DTO_TYPE, PROJECT_CONTAINS_NO_SCREENS, PROJECT_START_SCREEN_MISSING, PROJECT_START_SCREEN_UNKNOWN, EVENT_HANDLER_SCREEN_PARAMETER_DTO_WITHOUT_SCREEN_PARAMETER, EVENT_HANDLER_SCREEN_TO_OPEN_UNKNOWN, EVENT_HANDLER_MISSING_PARAMETER_DTO, EVENT_HANDLER_WRONG_PARAMETER_DTO_TYPE, EVENT_HANDLER_UNKNOWN_CONTAINER, EVENT_CONTAINER_NOT_A_BUTTON, EVENT_HANDLER_SCREEN_TO_OPEN_AND_URL_TO_OPEN, TIMER_INTERVAL_TOO_SHORT, SElECT_BOX_NO_DTO_SPECIFIED, SELECT_BOX_UNKNOWN_DTO_SPECIFIED, SELECT_BOX_NO_FIELD_IN_DTO_SPECIFIED, SELECT_BOX_DTO_TYPE_UNKNOWN, SELECT_BOX_UNKNOWN_DTO_FIELD, SELECT_BOXDTO_BASIC_TYPE_WITH_NESTED_TYPE, SELECT_BOX_DTO_SUB_TYPE_UNKNOWN, SELECT_BOX_DTO_IS_NOT_A_LIST, SELECT_BOX_ID_DTO_FIELD_IS_MISSING, SELECT_BOX_LABEL_DTO_FIELD_IS_MISSING, SELECT_BOX_ID_DTO_FIELD_DOES_NOT_EXIST, SELECT_BOX_ID_DTO_FIELD_HAS_WRONG_TYPE, SELECT_BOX_LABEL_DTO_FIELD_DOES_NOT_EXIST, SELECT_BOX_LABEL_DTO_FIELD_HAS_WRONG_TYPE, CELL_INVISIBLE_WITHOUT_ID, LAYOUT_CONTAINER_INVISIBLE_WITHOUT_ID, LAYOUT_BAR_INVISIBLE_WITHOUT_ID, DTO_NO_FIELDS, DTO_FIELD_TYPE_UNKNOWN, BAR_PROBLEM_EMPTY_BAR, PROJECT_CONTAINS_NO_OUTPUTS, PROJECT_DEFINITION_COULD_NOT_READ_CHILD_NODES, PROJECT_OUTPUT_UNKNOWN_FLAVOR, PROJECT_OUTPUT_MISSING_SOURCE_DIR_PATH, PROJECT_OUTPUT_UNEXPECTED_ANDROID_PROJECT_PATH, PROJECT_OUTPUT_MISSING_ANDROID_PROJECT_PATH, PROJECT_OUTPUT_UNEXPECTED_SOURCE_DIR_PATH, SELECT_BOX_SELECTED_ID_DTO_FIELD_DOES_NOT_EXIST, BASIC_WIDGET_TEXT_DTO_FIELD_DOES_NOT_EXIST, SHARED_REPLY_INTERFACE_ID_USED_MULTIPLE_TIMES, SHARED_REPLY_INTERFACE_COULD_NOT_READ_CHILD_NODES, SHARED_REPLY_INTERFACE_NO_SCREENS_DEFINED, SHARED_REPLY_INTERFACE_UNKNOWN_SCREEN, SHARED_REPLY_INTERFACE_SCREEN_OCCURS_MULTIPLE_TIMES
    }

    private String message;
    private NodePath nodePath;
    private String attribute;
    private ProblemType type;

    public ProblemType getType() {
        return type;
    }

    public void setType(ProblemType type) {
        this.type = type;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public NodePath getNodePath() {
        return nodePath;
    }

    public void setNodePath(NodePath nodePath) {
        this.nodePath = nodePath;
    }

    public String getAttribute() {
        return attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

}
